---
# This playbook deploys a simple development environment.

- hosts: target
  remote_user: root
  become: yes
  become_method: sudo

  roles:
      - basics
      - clang
      - python
      - dotfiles
